apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: satis
  name: satis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: satis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: satis
    spec:
      containers:
        - args:
            - build
            - ./config.json
            - ./output
          image: composer/satis
          name: satis
          resources: {}
          volumeMounts:
            - mountPath: /build
              name: satis-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/andrewreid/Documents/local_projects/satis/trial/Satis/Docker_Compose
          name: satis-hostpath0
status: {}
