apiVersion: v1
kind: Pod
metadata:
  name: satis
  labels:
    name: satis
spec:
  containers:
  - name: satis
    image: composer/satis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /myinput
        name: "myinput"
      - mountPath: /myoutput
        name: "myoutput"
      - mountPath: /build
        name: "build"
    command: ["build","/myinput/config.json","/myoutput"]
  restartPolicy: Never

  volumes:
    - name: myinput
      hostPath:
        path: /input
        type: Directory
    - name: myoutput
      hostPath:
        path: /output
        type: Directory
    - name: build
      hostPath:
        path: /
        type: Directory